/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-dim": "#131313",
                "primary": "#ebffe2",
                "on-tertiary-fixed-variant": "#614000",
                "on-error-container": "#ffdad6",
                "tertiary-container": "#ffd69b",
                "surface-bright": "#393939",
                "on-surface": "#e2e2e2",
                "on-secondary": "#00390f",
                "secondary-fixed-dim": "#83da87",
                "on-secondary-fixed-variant": "#00531a",
                "on-primary-fixed": "#002203",
                "surface-variant": "#353535",
                "on-secondary-fixed": "#002106",
                "on-background": "#e2e2e2",
                "inverse-on-surface": "#303030",
                "tertiary-fixed": "#ffddaf",
                "inverse-surface": "#e2e2e2",
                "on-tertiary-fixed": "#281800",
                "surface": "#000000",
                "primary-fixed-dim": "#00e639",
                "surface-container-high": "#2a2a2a",
                "on-primary-fixed-variant": "#00530e",
                "on-secondary-container": "#89e18d",
                "on-primary-container": "#007117",
                "surface-container-lowest": "#0e0e0e",
                "secondary-container": "#006622",
                "secondary-fixed": "#9ef7a1",
                "primary-container": "#00ff41",
                "surface-container-highest": "#353535",
                "tertiary": "#fff8f2",
                "secondary": "#83da87",
                "on-error": "#690005",
                "on-tertiary": "#432c00",
                "surface-container-low": "#1b1b1b",
                "primary-fixed": "#72ff70",
                "surface-container": "#1f1f1f",
                "on-tertiary-container": "#825800",
                "outline": "#84967e",
                "on-primary": "#003907",
                "background": "#000000",
                "tertiary-fixed-dim": "#ffba43",
                "outline-variant": "#3b4b37",
                "error-container": "#93000a",
                "surface-tint": "#00e639",
                "on-surface-variant": "#b9ccb2",
                "inverse-primary": "#006e16",
                "error": "#ffb4ab"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Space Mono", "monospace"],
                "label": ["Space Mono", "monospace"]
            },
            borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
        },
    },
    plugins: [],
}
