/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container": "#0f1930",
                "outline": "#6d758c",
                "primary-dim": "#6063ee",
                "error": "#ff6e84",
                "surface-tint": "#a3a6ff",
                "outline-variant": "#40485d",
                "surface-container-low": "#091328",
                "on-primary-container": "#0a0081",
                "primary-fixed-dim": "#8387ff",
                "inverse-surface": "#faf8ff",
                "primary-container": "#9396ff",
                "error-container": "#a70138",
                "on-tertiary-fixed-variant": "#003e56",
                "tertiary-container": "#2db7f2",
                "tertiary": "#47c4ff",
                "tertiary-fixed-dim": "#1bafe9",
                "secondary-dim": "#8455ef",
                "surface-bright": "#1f2b49",
                "on-primary-fixed-variant": "#0e009d",
                "on-primary": "#0f00a4",
                "on-secondary-fixed": "#40009b",
                "surface-container-lowest": "#000000",
                "on-secondary-container": "#d9c8ff",
                "on-error-container": "#ffb2b9",
                "tertiary-dim": "#05a9e3",
                "secondary-container": "#5516be",
                "surface-container-high": "#141f38",
                "surface": "#060e20",
                "surface-dim": "#060e20",
                "on-error": "#490013",
                "background": "#060e20",
                "secondary-fixed-dim": "#ceb9ff",
                "secondary-fixed": "#dac9ff",
                "surface-container-highest": "#192540",
                "primary": "#a3a6ff",
                "tertiary-fixed": "#37bcf7",
                "on-tertiary-fixed": "#001a27",
                "on-background": "#dee5ff",
                "on-secondary": "#280067",
                "surface-variant": "#192540",
                "on-surface-variant": "#a3aac4",
                "on-tertiary": "#003b52",
                "on-tertiary-container": "#003044",
                "inverse-primary": "#494bd7",
                "primary-fixed": "#9396ff",
                "secondary": "#ac8aff",
                "on-surface": "#dee5ff",
                "error-dim": "#d73357",
                "on-primary-fixed": "#000000",
                "inverse-on-surface": "#4d556b",
                "on-secondary-fixed-variant": "#5f28c8"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "mono": ["JetBrains Mono", "monospace"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
        },
    },
    plugins: [],
}
